name: Publish Dockers

on:
  push:
    branches:
      - main

jobs:
  publish-nightly:
    name: "Publish Nightly"
    if: github.event_name != 'release'
    uses: ./.github/workflows/partial-publish.yaml
    with:
      tag: nightly
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
