name: Publish Release

on:
  push:
    tags:
      - v*

jobs:
  backend-tests:
    name: "Backend Server Tests"
    uses: ./.github/workflows/partial-backend.yaml

  frontend-tests:
    name: "Frontend and End-to-End Tests"
    uses: ./.github/workflows/partial-frontend.yaml

  publish-tag:
    name: "Publish Tag"
    uses: ./.github/workflows/partial-publish.yaml
    with:
      release: true
      tag: ${{ github.ref_name }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-docs:
    name: Deploy docs
    needs:
      - publish-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
          EXTRA_PACKAGES: build-base